MyFirstMVC/MyFirstMVC/Models/Phone.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstMVC.Models
{
    public class Phone
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "укажи название телефона")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "длина названия от 1 до 50")]
        public string Name { get; set; }

        [Required]
        [Range(1, 100000, ErrorMessage = "Недопустимое значение Цены")]
        public double Price { get; set; }

        [Required]
        public bool? Available { get; set; }

        [Required]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        [Required]
        public int CompanyId { get; set; }
        public Company Company { get; set; }

        public double? Average { get; set; }

        public IEnumerable<Order> Orders { get; set; }

        public IEnumerable<PhoneOnStock> Stocks { get; set; }

        public IEnumerable<Reviews> Reviews { get; set; }
    }

    

}

MyFirstMVC/MyFirstMVC/Controllers/PhoneController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyFirstMVC.Models;
using MyFirstMVC.ViewModel;

namespace MyFirstMVC.Controllers
{
    public class PhoneController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;

        public PhoneController(ApplicationDbContext context, IHostingEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public enum SortPhones
        {
            NameAsc,
            NameDesc,
            PriceAsc,
            PriceDesc,
            CategoryAsc,
            CategoryDesc,
            CompanyAsc,
            CompanyDesc,
            RaitingAsc,
            RaitingDesc
        }



        // GET: Phone
        public ActionResult Index(int? companyId, string Name, int? PriceFrom, int? PriceTo, bool? Exist, int? categoryId, SortPhones sortPhones = SortPhones.NameAsc, int page = 1)
        {
            List<Company> companies = _context.Companies.ToList();
            List<Category> categories = _context.Categories.ToList();


            IQueryable<Phone> phones = _context.Phones.Include(x => x.Company).Include(x => x.Category).OrderBy(x => x.Name);

            IndexViewModel ivm = new IndexViewModel();

            if (companyId.HasValue)
            {
                phones = phones.Where(p => p.Company.Id == companyId.Value);
                ivm.Company = companies.FirstOrDefault(c => c.Id == companyId.Value);
            }

            if(!string.IsNullOrWhiteSpace(Name))
            {
                phones = phones.Where(p => p.Name.Contains(Name, StringComparison.OrdinalIgnoreCase));
                ivm.Name = Name;
            }

            if(PriceFrom.HasValue)
            {
                phones = phones.Where(p => p.Price >= PriceFrom);
                ivm.PriceFrom = PriceFrom;
            }

            if (PriceTo.HasValue)
            {
                phones = phones.Where(p => p.Price <= PriceTo);
                ivm.PriceTo = PriceTo;
            }
            if (categoryId.HasValue)
            {
                if (categoryId != -1)
                {
                    phones = phones.Where(p => p.Category.Id == categoryId.Value);
                    ivm.Category = categories.FirstOrDefault(c => c.Id == categoryId.Value);
                }
                
            }

            if (Exist != false && Exist != null)
            {
                phones = phones.Where(p => p.Available == true);
                ivm.Exist = Exist;
            }

            
            
            ViewBag.Message = _context.Currencies;

            ViewBag.NameSort = sortPhones == SortPhones.NameAsc ? SortPhones.NameDesc : SortPhones.NameAsc;
            ViewBag.PriceSort = sortPhones == SortPhones.PriceAsc ? SortPhones.PriceDesc : SortPhones.PriceAsc;
            ViewBag.CategorySort = sortPhones == SortPhones.CategoryAsc ? SortPhones.CategoryDesc : SortPhones.CategoryAsc;
            ViewBag.CompanySort = sortPhones == SortPhones.CompanyAsc ? SortPhones.CompanyDesc : SortPhones.CompanyAsc;
            ViewBag.RaitingSort = sortPhones == SortPhones.RaitingAsc ? SortPhones.RaitingDesc : SortPhones.RaitingAsc;

            switch (sortPhones)
            {
                case SortPhones.NameAsc:
                    //ViewBag.NameSort = SortPhones.NameDesc;
                    phones = phones.OrderBy(p => p.Name);
                    break;
                case SortPhones.NameDesc:
                    phones = phones.OrderByDescending(p => p.Name);
                    break;
                case SortPhones.PriceAsc:
                    // ViewBag.PriceSort = SortPhones.PriceDesc;
                    phones = phones.OrderBy(p => p.Price);
                    break;
                case SortPhones.PriceDesc:
                    phones = phones.OrderByDescending(p => p.Price);
                    break;
                case SortPhones.CategoryAsc:
                    //ViewBag.CategorySort = SortPhones.CompanyDesc;
                    phones = phones.OrderBy(c => c.Category.Name);
                    break;
                case SortPhones.CategoryDesc:
                    phones = phones.OrderByDescending(c => c.Category.Name);
                    break;
                case SortPhones.CompanyAsc:
                    // ViewBag.CompanySort = SortPhones.CompanyDesc;
                    phones = phones.OrderBy(c => c.Company.Name);
                    break;
                case SortPhones.CompanyDesc:
                    phones = phones.OrderByDescending(c => c.Company.Name);
                    break;
                case SortPhones.RaitingAsc:
                    // ViewBag.CompanySort = SortPhones.CompanyDesc;
                    phones = phones.OrderBy(c => c.Average);
                    break;
                case SortPhones.RaitingDesc:
                    phones = phones.OrderByDescending(c => c.Average);
                    break;
            }
            //
            int pageSize = 3;
            //IQueryable<User> source = db.Users.Include(x => x.Company);
            var count = phones.Count();
            ivm.Phones = phones.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            ivm.PageViewModel = pageViewModel;
            

            ivm.Companies = companies;
            //ivm.Phones = phones;
            ivm.Categories = categories;
            
            foreach (var phone in ivm.Phones)
            {
                var reviews = _context.Reviews.Where(x => x.PhoneId == phone.Id).Select(p => p.Rating).ToArray();
                if (reviews.Length != 0)
                {
                    phone.Average = reviews.Average();
                }
                
            }

            return View(ivm);
        }

        public IActionResult Download(int id)
        {
            try
            {
                Phone phone = _context.Phones.FirstOrDefault(x => x.Id == id);
                string filePath = Path.Combine(_environment.ContentRootPath, $"InfoPhoneFile/Phone_{phone.Name}.txt");
                string fileType = "application/txt";
                string fileName = $"{phone.Name}.txt";
                if (!System.IO.File.Exists(filePath))
                {
                    throw new FileNotFoundException($"File Not Found by Phone {phone.Name}");
                }
                return PhysicalFile(filePath, fileType, fileName);
            }
            catch (Exception e)
            {
                ViewData["Message"] = e.Message;
                return View("404");
            }

        }
        // GET: Phone/Details/5
        public ActionResult Details(int id)
        {
            Phone phone = _context.Phones.Include(x => x.Company).Include(x => x.Category).FirstOrDefault(x => x.Id == id);
            if (phone == null)
            {
                return NotFound($"Сорян, телефона с id {id} нету");
            }
            ViewBag.Message = _context.Currencies;
            List<Reviews> reviews = _context.Reviews.Where(x => x.PhoneId == id).ToList();
            ViewData["Reviews"] = reviews;
            return View(phone);
        }

        
        public IActionResult Redirect(int id)
        {
            Phone phone = _context.Phones.FirstOrDefault(x => x.Id == id);
            string url = String.Empty;
            string IPhoneSite = "https://www.apple.com/ru/iphone/";
            string SonySite = "https://www.sony.ru/";
            if (phone.Name == "Iphone 4")
            {
                url = IPhoneSite;
            }
            else if(phone.Name == "Xperia")
            {
                url = SonySite;
            }
            return Redirect(url);
        }


        // GET: Phone/Create
        public ActionResult Create()
        {
            ViewData["Companies"] = _context.Companies.ToList();
            ViewData["Categories"] = _context.Categories.ToList();
            return View();
        }

        // POST: Phone/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Phone phone)
        {
            try
            {
                // TODO: Add insert logic here
                _context.Phones.Add(phone);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Phone/Edit/5
        public ActionResult Edit(int id)
        {
            Phone phone = _context.Phones.Include(x => x.Company).Include(x => x.Category).FirstOrDefault(x => x.Id == id);
            //Phone phone = _context.Phones.Include(x => x.CategoryId).FirstOrDefault(x => x.Id == id);
            ViewData["Companies"] = _context.Companies.ToList();
            ViewData["Categories"] = _context.Categories.ToList();
            return View(phone);
        }

        // POST: Phone/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Phone phone)
        {
            try
            {
                _context.Update(phone);
                _context.SaveChanges();
            }
            catch
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Phone/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Phone/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {

MyFirstMVC/MyFirstMVC/Views/Phone/Create.cshtml
@model MyFirstMVC.Models.Phone

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Phone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="ExistPhone">
                @Html.CheckBox("Available")
                <label>Only Exist Phones</label>
                @*<input id="Check" name="Check" type="checkbox" value="true">*@
                <input name="Available" type="hidden" value="false">
            </div>
            <div class="form-group">
                <div class="col-12 col-lg-2 CompanyNameInFilter">
                    @Html.Label("Companies")
                </div>
                <select name="companyId" class="form-control">
                    <option> </option>
                    @foreach (Company comp in (List<Company>)(ViewData["Companies"]))
                    {
                        <option value="@comp.Id">@comp.Name</option>
                    }
                </select>
            </div>
            <div class="col-12 col-lg-2 CompanyNameInFilter">
                @Html.Label("Categories")
            </div>
            <select name="categoryId" class="form-control">
                <option> </option>
                @foreach (Category comp in (List<Category>)(ViewData["Categories"]))
                {
                    <option value="@comp.Id">@comp.Name</option>
                }
            </select>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstMVC/MyFirstMVC/Views/Phone/Details.cshtml
@model MyFirstMVC.Models.Phone

@{

    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Phone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt>
            @Html.DisplayName("USD")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        @foreach (var item in (IEnumerable<Currency>)ViewBag.Message)
        {
            <dt>
                @Html.DisplayFor(modelitem => item.CurrencyCode)
            </dt>
            <dd>
                @(item.CurrencyRate * Model.Price)
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        @{List<Reviews> reviews = (List<Reviews>)ViewData["Reviews"];}
        @{int a = 1; }


        @if (reviews.Count != 0)
        {
            int count = 0;
            int summa = 0;
            foreach (var review in reviews)
            {
                summa += review.Rating;
                count++;
            }
            int srednyaya = summa / count;

            <h2>Средняя оценка - @srednyaya</h2>

            <h2>Reviews</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Rating</th>
                        <th scope="col">Person Name</th>
                        <th scope="col">Review</th>
                    </tr>
                </thead>
                @foreach (var item in (List<Reviews>)ViewData["Reviews"])
                {   
                    <tbody>
                        <tr>
                            <th scope="row">@a</th>
                            <td>@Html.DisplayFor(modelitem => item.Rating)</td>
                            <td>@Html.DisplayFor(modelitem => item.NamePersonReview)</td>
                            <td>@Html.DisplayFor(modelitem => item.Review)</td>
                        </tr>
                    </tbody>
                    a++;
                }
            </table>
        }

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a> |
    <a asp-action="Redirect" asp-route-id="@Model.Id">Go to the manufacturer's website</a> |
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstMVC/MyFirstMVC/Views/Phone/Edit.cshtml
@model MyFirstMVC.Models.Phone

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Phone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="col-12 col-lg-2 CompanyNameInFilter">
                    @Html.Label("Companies")
                </div>
                <select name="companyId" class="form-control">
                    @foreach (Company comp in (List<Company>)(ViewData["Companies"]))
                    {
                        if (Model.Company != null && Model.Company.Id == comp.Id)
                        {
                            <option value="@comp.Id" selected="selected">@comp.Name</option>
                        }
                        else
                        {
                            <option value="@comp.Id">@comp.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="col-12 col-lg-2 CompanyNameInFilter">
                @Html.Label("Categories")
            </div>
            <select name="categoryId" class="form-control">
                @foreach (Category comp in (List<Category>)(ViewData["Categories"]))
                {
                    if (Model.Category != null && Model.Category.Id == comp.Id)
                    {
                        <option value="@comp.Id" selected="selected">@comp.Name</option>
                    }
                    else
                    {
                        <option value="@comp.Id">@comp.Name</option>
                    }
                }
            </select>
            <div class="form-group">
                <input type="submit" value="Save" asp-route-id="@Model" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstMVC/MyFirstMVC/Views/Phone/Index.cshtml
@using MyFirstMVC.ViewModel

@model IndexViewModel

@{

    ViewData["Title"] = "Home Page";

}

@using (Html.BeginForm("Index", "Phone", FormMethod.Get))

{
    <p>
        <a asp-action="Create">Create Phone</a>
    </p>

    <div class="PhoneName">
        @Html.Label("Name", "Phone Name:")
        @Html.TextBox("Name", Model.Name)

    </div>
    <div class="container CompanyNameFilter">
        <div class="row">
            <div class="col-12 col-lg-2 CompanyNameInFilter">
                @Html.Label("Companies Name:")
            </div>
            <div class="col-12 col-lg-4">
                <select name="companyId" class="form-control">
                    <option> </option>
                    @foreach (Company comp in Model.Companies)
                    {
                        if (Model.Company != null && Model.Company.Id == comp.Id)
                        {
                            <option value="@comp.Id" selected="selected">@comp.Name</option>
                        }
                        else
                        {
                            <option value="@comp.Id">@comp.Name</option>
                        }
                    }
                </select>
            </div>
        </div>
    </div>
    <div class="FilterByPrice">
        @Html.Label("PriceFrom", "PriceFrom:")
        @Html.TextBox("PriceFrom", Model.PriceFrom)
        @Html.Label("PriceTo", "PriceTo:")
        @Html.TextBox("PriceTo", Model.PriceTo)
    </div>
    <div class="ExistPhone">
        @Html.CheckBox("Exist", Model.Exist)
        <label>Only Exist Phones</label>
        @*<input id="Check" name="Check" type="checkbox" value="true">*@
        <input name="Check" type="hidden" value="false">
    </div>
    <div class="CategoryFilter">
        @Html.RadioButton("categoryId", -1, true)
        <span>All Categories</span> <br />

        @foreach (Category category in Model.Categories)
        {
            if (Model.Category != null && Model.Category.Id == category.Id)
            {
                @Html.RadioButton("categoryId", category.Id, true)
            }
            else
            {
                @Html.RadioButton("categoryId", category.Id)
            }

            <span>@category.Name</span> <br />
        }

    </div>
    <div class="btn-sbm">
        <input type="submit" class="btn btn-info" />
    </div>
}



<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col"><a asp-action="Index" asp-route-sortPhones="@ViewBag.NameSort">Name</a></th>
            <th scope="col"><a asp-action="Index" asp-route-sortPhones="@ViewBag.CompanySort">Company</a></th>
            <th scope="col"><a asp-action="Index" asp-route-sortPhones="@ViewBag.CategorySort">Category</a></th>
            <th scope="col"><a asp-action="Index" asp-route-sortPhones="@ViewBag.PriceSort">USD</a></th>

            @foreach (var item in (IEnumerable<Currency>)ViewBag.Message)
            {
                <th scope="col"><a asp-action="Index" asp-route-sortPhones="@ViewBag.PriceSort">@item.CurrencyCode </a></th>
            }
            <th><a asp-action="Index" asp-route-sortPhones="@ViewBag.RaitingSort">Average Raiting</a></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Phone p in Model.Phones)
        {
            <tr>
                <th scope="row">@p.Name</th>
                <th>
                    <a asp-area="" asp-controller="Phone" asp-action="Index" asp-route-companyId="@p.CompanyId">@p.Company.Name</a>
                </th>
                <th>@p.Category?.Name</th>
                <th>@p.Price</th>

                @foreach (var item in (IEnumerable<Currency>)ViewBag.Message)
                {
                    <th>@(item.CurrencyRate * p.Price)</th>
                }
                <th>@p.Average</th>
                <td>
                    <a asp-action="Edit" asp-route-id="@p.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@p.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@p.Id">Delete</a> |
                    <a asp-controller="Reviews" asp-action="Create" asp-route-id="@p.Id">Add review</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-default btn">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}